PL/Controllers/SemestreCargaMasivaController.cs
using Microsoft.AspNetCore.Mvc;
using IHostingEnvironment = Microsoft.AspNetCore.Hosting.IHostingEnvironment;

namespace PL.Controllers
{
    public class SemestreCargaMasivaController : Controller
    {

        private IHostingEnvironment environment;
        private IConfiguration configuration;
        public SemestreCargaMasivaController(IHostingEnvironment _environment, IConfiguration _configuration)
        {
            environment = _environment;
            configuration = _configuration;
        }

        [HttpGet]
        public IActionResult CargaMasiva()
        {
            ML.Result result = new ML.Result();

            return View(result);
        }

        [HttpPost]
        public IActionResult CargaMasiva(ML.Semestre semestre)
        {
            IFormFile file = Request.Form.Files["fileExcel"];

            if (HttpContext.Session.GetString("PathArchivo") == null)
            {
                if (file != null)
                {
                    //.xsls , .xls, .csv
                    //obtener el nombre de nuestro archivo
                    string fileName = Path.GetFileName(file.FileName);

                    string folderPath = configuration["PathFolder"];
                    string extensionArchivo = Path.GetExtension(file.FileName).ToLower();
                    string extensionAppsettings = configuration["TipoExcel"];
                    if (extensionArchivo == extensionAppsettings)
                    {
                        //crear una copia del archivo cargado
                        string filePath = Path.Combine(environment.ContentRootPath, folderPath, Path.GetFileNameWithoutExtension(fileName)) + '-' + DateTime.Now.ToString("yyyyMMddHHmmss") + ".xlsx";

                        if (!System.IO.File.Exists(filePath))
                        {
                            using (FileStream stream = new FileStream(filePath, FileMode.Create))
                            {
                                file.CopyTo(stream);
                            }

                            string connString = configuration["ExcelConString"] + filePath;//cadena de conexion y ruta especifica del archivo

                            //crear un metodo en BL.Semestre
                            ML.Result resultExcelDt = BL.Semestre.ConvertExcelToDataTable(connString);

                            if (resultExcelDt.Correct)
                            {
                                ML.Result resultValidacion = BL.Semestre.ValidarExcel(resultExcelDt.Objects);

                                if (resultValidacion.Objects.Count == 0)
                                {
                                    resultValidacion.Correct = true;
                                    HttpContext.Session.SetString("PathArchivo", filePath);//crear la session
                                }

                                return View(resultValidacion);
                            }
                            else
                            {
                                ViewBag.Message = "El excel no contiene registros";
                            }
                        }

                    }
                    else
                    {
                        ViewBag.Message = "El archivo que se intenta procesar no es un excel";
                    }

                }
            }
            else
            {
                string rutaArchivoExcel = HttpContext.Session.GetString("PathArchivo");
                string connectionString = configuration["ExcelConString"] + rutaArchivoExcel;

                ML.Result resultData = BL.Semestre.ConvertExcelToDataTable(connectionString);
                if (resultData.Correct)
                {
                    ML.Result resultErrores = new ML.Result();
                    resultErrores.Objects = new List<object>();

                    foreach (ML.Semestre semestreItem in resultData.Objects)
                    {

                        ML.Result resultAdd = BL.Semestre.Add(semestreItem);
                        if (!resultAdd.Correct)
                        {
                            resultErrores.Objects.Add("No se insertó el Semestre con nombre: " + semestreItem.Nombre + " Error: " + resultAdd.ErrorMessage);
                        }
                    }
                    if (resultErrores.Objects.Count > 0)
                    {

                        string fileError = Path.Combine(environment.WebRootPath, @"~\Files\logErrores.txt");
                        using (StreamWriter writer = new StreamWriter(fileError))
                        {
                            foreach (string ln in resultErrores.Objects)
                            {
                                writer.WriteLine(ln);
                            }
                        }
                        ViewBag.Message = "Las Alumnos No han sido registrados correctamente";
                    }
                    else
                    {
                        //borrar session
                        ViewBag.Message = "Las Alumnos han sido registrados correctamente";
                    }

                }

            }
            return PartialView("Modal");
        }
    }
}

PL/Views/SemestreCargaMasiva/CargaMasiva.cshtml
@model ML.Result
@{
    ViewData["Title"] = "CargaMasiva";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div class="container">
    <h1>Carga Masiva de Semestres</h1>
    <h5>Seleccione con que tipo de archivo desea hacer la carga</h5>
    <hr />

    <div class="row">
        <div class="col-md-6">
            <a><input type="submit" value="Excel" class="btn btn-success col-md-12" id="excel" /></a>
        </div>
        <div class="col-md-6">
            <a><input type="submit" value="TXT" class="btn btn-info col-md-12" id="txt" /></a>
        </div>
    </div>

    @using (Html.BeginForm("CargaMasiva", "SemestreCargaMasiva", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        <div class="row g-3" id="input" style="display:none;">
            <div class="col-md-6">
                <div class="input-group">
                    <span class="input-group-text" id="basic-addon1"><i class="bi bi-file-earmark-text-fill" style="color: lightseagreen"></i></span>
                    <input type='file' class="form-control" name="FileExcel" />
                </div>
            </div>
            @if (!Model.Correct)
            {
                <div class="row g-3">
                    <div class="col-md-1">
                        <a><input type="submit" value="Procesar" class="btn btn-success" /></a>
                        <br />
                    </div>
                </div>
            }
            else
            {
                <div class="row g-3">
                    <div class="col-md-1">
                        <a><input type="submit" value="Insertar" class="btn btn-success" /></a>
                        <br />
                    </div>
                </div>
            }
        </div>
        <br />
    }
    <div class="row">
        <div class="col-md-12">
            @if (Model.Objects != null)
            {
                @if (Model.Objects.Count > 0)
                {
                    <table class="table table-dark table-bordered table-responsive">
                        <thead>
                            <tr class="text-center">
                                <td>IdRegistro</td>
                                <td>Error</td>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (ML.ErrorExcel error in Model.Objects)
                            {
                                <tr class="text-center">
                                    <td>@error.IdRegistro</td>
                                    <td>@error.Mensaje</td>
                                </tr>
                            }
                        </tbody>
                    </table>
                }
            }
            else
            {

            }
        </div>
    </div>
</div>


@section Scripts
    {
    <script src="~/lib/jquery/dist/jquery.js"></script>
    <link rel="stylesheet" href="//code.jquery.com/ui/1.13.2/themes/base/jquery-ui.css">
    <link rel="stylesheet" href="/resources/demos/style.css">
    <script type="text/javascript">


        $('#excel').click(function () {
            $('#input').toggle('slow', function () {
            });
        });

    </script>
}