PL/Controllers/AlumnoController.cs
using Microsoft.AspNetCore.Mvc;

namespace PL.Controllers
{
    public class AlumnoController : Controller
    {
        //[HttpGet]
        //public ActionResult GetAll()
        //{
        //    ML.Alumno alumno = new ML.Alumno();
        //    ML.Result result = BL.Alumno.GetAll(alumno);


        //    if (result.Correct)
        //    {
        //        alumno.Alumnos = result.Objects;
        //    }
        //    else
        //    {
        //        ViewBag.Message = "Ocurrio un error al hacer la consulta de alumnos" + result.ErrorMessage;
        //    }

        //    return View(alumno);
        //}
        [HttpGet]
        public ActionResult GetAll()
        {
            ML.Alumno resultAlumnos = new ML.Alumno();
            resultAlumnos.Alumnos = new List<object>();
            using (var client = new HttpClient())
            {


                client.BaseAddress = new Uri("http://localhost:5047/api/");

                var responseTask = client.GetAsync("Alumno/GetAll");
                responseTask.Wait(); //esperar a que se resuelva la llamada al servicio

                var result = responseTask.Result;

                if (result.IsSuccessStatusCode)
                {
                    var readTask = result.Content.ReadAsAsync<ML.Result>();
                    readTask.Wait();

                    foreach (var resultItem in readTask.Result.Objects)
                    {
                        ML.Alumno resultItemList = Newtonsoft.Json.JsonConvert.DeserializeObject<ML.Alumno>(resultItem.ToString());
                        resultAlumnos.Alumnos.Add(resultItemList);
                    }
                }
            }
            return View(resultAlumnos);
        }

        [HttpPost]
        public ActionResult GetAll(ML.Alumno alumno)
        {

            ML.Result result = BL.Alumno.GetAll(alumno);



            if (result.Correct)
            {
                alumno.Alumnos = result.Objects;
            }
            else
            {
                ViewBag.Message = "Ocurrio un error al hacer la consulta de alumnos" + result.ErrorMessage;
            }

            return View(alumno);
        }

        [HttpGet]
        public ActionResult Form(int? idAlumno)
        {
            ML.Result resultSemestres = BL.Semestre.GetAll();
            //ML.Result resultPlanteles = BL.Plantel.GetAll();

            ML.Alumno alumno = new ML.Alumno();
            alumno.Semestre = new ML.Semestre();

            alumno.Horario = new ML.Horario();
            alumno.Horario.Grupo = new ML.Grupo();
            alumno.Horario.Grupo.Plantel = new ML.Plantel();

            if (resultSemestres.Correct)
            {
                alumno.Semestre.Semestres = resultSemestres.Objects;
                //alumno.Horario.Grupo.Plantel.Planteles = resultPlanteles.Objects;
            }
            //add o update
            if (idAlumno == null)
            {
                //add
                //mostrar formulario vacio
                return View(alumno);
            }

            else
            {

                using (var client = new HttpClient())
                {

                    client.BaseAddress = new Uri("http://localhost:5047/api/");
                    //client.BaseAddress = new Uri(configuration["WebApi"]);
                    var responseTask = client.GetAsync("Alumno/GetById/" + idAlumno);
                    responseTask.Wait();
                    var resultAPI = responseTask.Result;
                    if (resultAPI.IsSuccessStatusCode)
                    {
                        var readTask = resultAPI.Content.ReadAsAsync<ML.Result>();
                        readTask.Wait();
                        ML.Alumno resultItemList = new ML.Alumno();
                        resultItemList = Newtonsoft.Json.JsonConvert.DeserializeObject<ML.Alumno>(readTask.Result.Object.ToString());
                        alumno = resultItemList;

                    }
                }
                return View(alumno);


                //bl.alumno.getbyid(idAlumno.value)
                //ML.Result result = BL.Alumno.GetByIdEF(idAlumno.Value);

                if (alumno != null)
                {
                    //    //update
                    //    //muestra el formulario con la informacion del alumno
                    //    alumno = (ML.Alumno)result.Object;


                    //    ML.Result resultGrupos = BL.Grupo.GetByIdPlantel(alumno.Horario.Grupo.Plantel.IdPlantel);

                    //    //ML.Result resultMunicipios = BL.Municipio.GetByIdEstado(alumno.Direccion.Colonia.Municipio.Estado.IdEstado);

                    //    alumno.Horario.Grupo.Grupos = resultGrupos.Objects;
                    //    alumno.Semestre.Semestres = resultSemestres.Objects;
                    //    alumno.Horario.Grupo.Plantel.Planteles = resultPlanteles.Objects;
                    //    //alumno.Direccion.Colonia.Municipio.Municipio = resultMunicipios.Objects;

                    //    return View(alumno);
                    return View();

                }
                else
                {
                    ViewBag.Message = "Ocurrio un error al hacer la consulta del alumno ";
                    return View("Modal");
                }


            }
        }

        //[HttpPost] //metodo sin servicios web
        //public ActionResult Form(ML.Alumno alumno)
        //{
        //    if (ModelState.IsValid)//validar si se cumplieron todas las data annotations
        //    {
        //        IFormFile file = Request.Form.Files["inpImagen"];

        //        if (file != null)
        //        {
        //            alumno.Imagen = Convert.ToBase64String(ConvertToBytes(file));

        //        }

        //        ML.Result result = new ML.Result();
        //        //add o update
        //        if (alumno.IdAlumno == 0)
        //        {
        //            //add
        //            result = BL.Alumno.Add(alumno);
        //            if (result.Correct)
        //            {
        //                ViewBag.Message = "Se inserto correctamente el alumno";
        //            }
        //            else
        //            {
        //                ViewBag.Message = "Ocurrio un error al insertar el alumno" + result.ErrorMessage;
        //            }

        //        }
        //        else
        //        {

        //            //update
        //            //result = BL.Alumno.UpdateEF(alumno);
        //            //if (result.Correct)
        //            //{
        //            //    ViewBag.Message = "Se actualizo correctamente el registro del alumno";
        //            //}
        //            //else
        //            //{
        //            //    ViewBag.Message = "Ocurrio un error al actualizar el registro del alumno" + result.ErrorMessage;
        //            //}
        //        }

        //        return View("Modal");
        //    }
        //    else
        //    {
        //        ML.Result resultSemestres = BL.Semestre.GetAll();
        //        //ML.Result resultPlanteles = BL.Plantel.GetAll();

        //        alumno.Semestre = new ML.Semestre();

        //        alumno.Horario = new ML.Horario();
        //        alumno.Horario.Grupo = new ML.Grupo();
        //        alumno.Horario.Grupo.Plantel = new ML.Plantel();
        //        alumno.Semestre.Semestres = resultSemestres.Objects;
        //        //alumno.Horario.Grupo.Plantel.Planteles = resultPlanteles.Objects;
        //        return View(alumno);
        //    }

        //}
        [HttpPost] //metodo con servicios web
        public ActionResult Form(ML.Alumno alumno)
        {
            if (ModelState.IsValid)//validar si se cumplieron todas las data annotations
            {
                IFormFile file = Request.Form.Files["inpImagen"];

                if (file != null)
                {
                    alumno.Imagen = Convert.ToBase64String(ConvertToBytes(file));

                }

                ML.Result result = new ML.Result();
                //add o update
                if (alumno.IdAlumno == 0)
                {
                    //add
                    using (var client = new HttpClient())
                    {
                        client.BaseAddress = new Uri("http://localhost:5047/api/");

                        //HTTP POST
                        var postTask = client.PostAsJsonAsync<ML.Alumno>("Alumno/Add", alumno);
                        postTask.Wait();

                        var resultAlumno = postTask.Result;
                        if (resultAlumno.IsSuccessStatusCode)
                        {
                            ViewBag.Mensaje = "Se ha insertado el usuario";
                            return PartialView("Modal");
                        }

                        else
                        {
                            ViewBag.Mensaje = "No se inserto el usuario";
                            return PartialView("Modal");
                        }
                    }

                }
                else
                {
                    using (var client = new HttpClient())
                    {
                        client.BaseAddress = new Uri("http://localhost:5047/api/");

                        //HTTP POST
                        var postTask = client.PutAsJsonAsync<ML.Alumno>("Alumno/Update/" + alumno.IdAlumno, alumno);
                        postTask.Wait();

                        var resultAlumno = postTask.Result;
                        if (resultAlumno.IsSuccessStatusCode)
                        {
                            ViewBag.Mensaje = "Se ha actualizado el alumno";
                            return PartialView("Modal");
                        }
                    }
                    return PartialView("Modal");
                }
            }
            else
            {

PL/Controllers/SemestreController.cs
using Microsoft.AspNetCore.Mvc;

namespace PL.Controllers
{
    public class SemestreController : Controller
    {
        public ActionResult GetAll()
        {
            ML.Result result = BL.Semestre.GetAll();

            ML.Semestre semestre = new ML.Semestre();
            semestre.Semestres = result.Objects;

            return View(semestre);
        }
        [HttpGet]
        public ActionResult Form()
        {
            //ML.Result resultArea = BL.Area.GetAll();

            //ML.Departamento departamento = new ML.Departamento();

            //departamento.Area = new ML.Area();
            //departamento.Area.Areas = resultArea.Objects;

            //return View(departamento);
            return View();
        }
        [HttpPost]
        public ActionResult Form(ML.Semestre semestre)
        {
            ML.Result result = BL.Semestre.Add(semestre);
            if (result.Correct)
            {
                ViewBag.Message = "Se ha insertado el semestre";
            }
            else
            {
                ViewBag.Message = "Se ha insertado el semestre";
            }
            return PartialView("Modal");
        }
    }
}

PL/Views/Semestre/Form.cshtml
@model ML.Semestre
@{
    ViewData["Title"] = "GetAll";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div class="container">
    <div class="row">
        <div class="col-md-12">
            <h2>Alumno</h2>
        </div>
    </div>

    @using (Html.BeginForm("Form", "Semestre", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        <div class="form-horizontal">
            <div class="form-group">
                <div class="col-md-3">
                    @Html.LabelFor(model => model.IdSemestre, new { @class = "visually-hidden" })

                    @Html.TextBoxFor(model => model.IdSemestre, new { @class = "visually-hidden form-control" })
                    @Html.ValidationMessageFor(model => model.IdSemestre)
                </div>
            </div>
            <div class="row">

                <div class="col-md-3">
                    @Html.LabelFor(model => model.Nombre)
                    <div class="input-group">
                        <span class="input-group-text" id="basic-addon1"><i class="fa-solid fa-user-plus fa-fade" style="color:greenyellow"></i></span>
                        @Html.TextBoxFor(model => model.Nombre, new { @class = "form-control", @id = "txtNombre", @onkeypress="SoloLetras(event, 'lblNombre', 'txtNombre')" })
                        @Html.ValidationMessageFor(model => model.Nombre)

                    </div>
                </div>
            </div>


            <div class="form-group">
                <div class="col-md-3">
                    <input type="submit" value="Guardar" class="btn btn-success" />
                    @Html.ActionLink("Regresar", "GetAll", "Alumno", htmlAttributes: new { @class = "btn btn-danger" })
                </div>
            </div>
        </div>
    }
</div>
       

PL/Views/Semestre/GetAll.cshtml
@model ML.Semestre
@{
    ViewData["Title"] = "GetAll";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div class="container">
    <section>

        <h1 class="text-center">Lista de Semestres</h1>
        <p>
            En este modulo puedes visualizar a los semestres existentes,<br />
            agregar, modificar y eliminar un alumno
        </p>
    </section>
    <section>

        <div style="float:right;">
            <div class="row">
                @Html.ActionLink("Agregar", "Form", "Semestre", htmlAttributes: new { @class = "btn btn-success bi bi-person-plus-fill" })
            </div>
        </div>
    </section>
    <hr />
    <section>
        @if (Model.Semestres == null)
        {
            <div class="row">
                <div class="alert alert-danger" role="alert">
                    @ViewBag.Message
                </div>
            </div>
        }
        else
        {


            <table class="table table-dark table-hover table-bordered table-responsive">
                <thead>
                    <tr>
                        <td class="text-center" style=" font-weight:bold;">Editar</td>
                        <td class="visually-hidden">IdSemestre</td>
                        <td class="text-center" style="font-weight:bold;">Nombre</td>
                        <td class="text-center" style=" font-weight:bold;">Eliminar</td>
                    </tr>
                </thead>
                <tbody>

                    @foreach (ML.Semestre semestre in Model.Semestres)
                    {
                        <tr>
                            <td class="text-center"><a class="btn btn-warning bi bi-pencil-square" href="@Url.Action("Form", "Semestre", new { IdSemestre = semestre.IdSemestre })"></a></td>
                            <td class="visually-hidden">@semestre.IdSemestre</td>
                            <td>@semestre.Nombre </td>             
                            <td class="text-center"><a class="btn btn-danger bi bi-trash" href="@Url.Action("Delete", "Semestre", new { IdSemestre = semestre.IdSemestre})" onclick="return confirm('Estas seguro que deseas eliminar este registro?');"></a></td>
                        </tr>
                    }
                </tbody>
            </table>

        }



    </section>
</div>